[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/tags/projects"
    weight = 30
[[main]]
    identifier = "projects-circl"
    parent = "projects"
    name = "CIRCL"
    url = "/projects/CIRCL"
    weight = 31
[[main]]
    identifier = "projects-cyberlux"
    parent = "projects"
    name = "CyberLux"
    url = "/projects/CyberLux"
    weight = 32
[[main]]
    identifier = "projects-nc3"
    parent = "projects"
    name = "NC3"
    url = "/projects/NC3"
    weight = 33
