[[main]]
    identifier = "projects"
    name = "Projects"
    weight = 30
[[main]]
    identifier = "projects-circl"
    parent = "projects"
    name = "CIRCL"
    url = "/projects/CIRCL"
    weight = 31
[[main]]
    identifier = "projects-cyberlux"
    parent = "projects"
    name = "CyberLux"
    url = "/projects/CyberLux"
    weight = 32
[[main]]
    identifier = "projects-nc3"
    parent = "projects"
    name = "NC3"
    url = "/projects/NC3"
    weight = 33
[[main]]
    identifier = "services"
    name = "Services"
    weight = 40
[[main]]
    identifier = "services-circl"
    parent = "services"
    name = "CIRCL"
    url = "/services/CIRCL"
    weight = 41
[[main]]
    identifier = "services-lhc"
    parent = "services"
    name = "LHC"
    url = "/services/LHC"
    weight = 42
[[main]]
    identifier = "services-nc3"
    parent = "services"
    name = "NC3"
    url = "/services/NC3"
    weight = 43
