
[[main]]
    name = "Projects"
    weight = 30
[[main]]
    parent = "Projects"
    name = "CIRCL"
    url = "/projects/CIRCL"
    weight = 31
[[main]]
    parent = "Projects"
    name = "NC3"
    url = "/projects/NC3"
    weight = 32
[[main]]
    parent = "Projects"
    name = "CyberLux"
    weight = 33
[[main]]
    name = "Services"
    url = "/services"
    weight = 40
[[main]]
    parent = "Services"
    name = "NC3"
    url = "/services/nc3"
    weight = 41
[[main]]
    parent = "Services"
    name = "CIRCL"
    url = "/services/circl"
    weight = 42
[[main]]
    parent = "Services"
    name = "LHC"
    url = "/services/LHC"
    weight = 43
