 
[[main]]
    name = "Projects"
    weight = 30
[[main]]
    parent = "Projects"
    name = "MONARC"
    url = "/monarc"
    weight = 31
[[main]]
    parent = "Projects"
    name = "Fit4CyberSecurity"
    url = "/Fit4CyberSecurity"
    weight = 32
[[main]]
    parent = "Projects"
    name = "MOSP"
    url = "/mosp"
    weight = 33
[[main]]
    parent = "Projects"
    name = "Observatory"
    url = "/observatory"
    weight = 34
[[main]]
    parent = "Projects"
    name = "More projects …"
    url = "/projects"
    weight = 39

