baseURL = 'https://NC3-LU.github.io'
languageCode = 'en-us'
title = 'Open Source at NC3 - LU'
copyright = "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"
enableRobotsTXT = true

# theme as git submodule
theme = "hugo-arcana"

[taxonomies]
    tag = "tags"

[permalinks]
     post = '/:year/:month/:day/:slug/'

[params]
    description = "National Coordination Center - NC3-LU"
    show_post_dates = true

    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/NC3-LU"

[params.footer]
    [[params.footer.links]]
        header = "Ecosystem"
        [[params.footer.links.links]]
            title = "Luxembourg House of Cybersecurity"
            url = "https://www.cybersecurity.lu/lhc"
        [[params.footer.links.links]]
            title = "CIRCL"
            url = "https://www.circl.lu"
