baseURL = 'https://code.lhc.lu'
languageCode = 'en-uk'

# homepage params
title = 'Code @ LHC'
description = "Inventory of **Open Source Software** of the *Luxembourg House of Cybersecurity*"
main_button = "Discover our Projects"
main_button_sub = "powered by the two centres hosted at the Luxembourg House of Cybersecurity: [CIRCL](https://circl.lu) & [NC3](https://nc3.lu)"
subtitle = "**Open source software is more important than ever!** *And we are committed to improve and cyber secure the society through open technologies.*"
copyright = "The Luxembourg House of Cybersecurity - Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"

enableRobotsTXT = true
Paginate = 4

theme = "kode"

[taxonomies]
    tag = "tags"

[permalinks]
     post = '/:year/:month/:day/:slug/'

[[menu.main]]

[[menu.footer]]
    name = "Projects"
    weight = 10
    url = "/projects/"
[[menu.footer]]
    name = "Contact"
    weight = 90
    url = "https://lhc.lu/contact"

[params]
    description = "Luxembourg House of Cybersecurity"
    show_post_dates = true
    RSSLink = "/index.xml"
    author = "LHC" # add your company name
    github = "https://github.com/NC3-LU" # add your github profile name
    twitter = "houseofcyber_lu" # add your twitter profile
    email = "code@lhc.lu"

    [[params.social]]
        title = "CIRCL GitHub account"
        icon = "fa-github"
        url = "https://github.com/CIRCL"

    [[params.social]]
        title = "NC3 GitHub account"
        icon = "fa-github"
        url = "https://github.com/NC3-LU"

    [[params.social]]
        title = "CyberSecurityLuxembourg GitHub account"
        icon = "fa-github"
        url = "https://github.com/CybersecurityLuxembourg"

