baseURL = 'https://code.lhc.lu'
languageCode = 'en-us'
title = 'Open Source at NC3 - LU'
copyright = "The National Cybersecurity Competence Centre of Luxembourg - Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"
enableRobotsTXT = true

# theme as git submodule
theme = "hugo-arcana"

[taxonomies]
    tag = "tags"

[permalinks]
     post = '/:year/:month/:day/:slug/'

[params]
    description = "National Cybersecurity Competence Centre - NC3-LU"
    show_post_dates = true

    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/NC3-LU"

[params.footer]
    [[params.footer.links]]
        header = "Ecosystem"
        [[params.footer.links.links]]
            title = "CIRCL"
            url = "https://www.circl.lu"
        [[params.footer.links.links]]
            title = "NC3"
            url = "https://www.nc3.lu"
        [[params.footer.links.links]]
            title = "Luxembourg House of Cybersecurity"
            url = "https://www.cybersecurity.lu/lhc"
        [[params.footer.links.links]]
            title = "National Coordination Centres"
            url = "https://cybersecurity-centre.europa.eu/nccs_en"
    [[params.footer.links]]
        header = "Get In Touch"
        [[params.footer.links.links]]
            title = "Our PGP key"
            url = "https://pgp.circl.lu/pks/lookup?op=hget&search=5632abce12a3d6e5355ca37025b2ac32"
